const BASE = import.meta.env.BASE_URL;

// 2D view: a pre-rendered nilearn glass-brain projection (sagittal · coronal ·
// axial) with anatomical outlines. Parcellated atlases show their important
// parcels filled; node atlases show markers. Generated by
// scripts/build-parcellation-meshes.py --glass-only → public/assets/atlases/<key>_glass.png
export default function GlassBrain2D({ atlas }) {
  return (
    <figure className="my-2">
      <div className="rounded-xl overflow-hidden border border-rule/20" style={{ background: "#000" }}>
        <img
          src={`${BASE}assets/atlases/${atlas.key}_glass.png`}
          alt={`${atlas.label} glass-brain projection`}
          className="block w-full h-auto"
        />
      </div>
      <figcaption className="font-serif text-sm text-ink2 mt-3 text-center italic">
        Glass-brain projection of {atlas.label} — colour marks the important regions.
      </figcaption>
    </figure>
  );
}
